var namespace_m_r =
[
    [ "Adapter", "namespace_m_r_1_1_adapter.html", "namespace_m_r_1_1_adapter" ],
    [ "App", "namespace_m_r_1_1_app.html", "namespace_m_r_1_1_app" ],
    [ "Connectome", "namespace_m_r_1_1_connectome.html", "namespace_m_r_1_1_connectome" ],
    [ "DWI", "namespace_m_r_1_1_d_w_i.html", "namespace_m_r_1_1_d_w_i" ],
    [ "File", "namespace_m_r_1_1_file.html", "namespace_m_r_1_1_file" ],
    [ "Filter", "namespace_m_r_1_1_filter.html", "namespace_m_r_1_1_filter" ],
    [ "Formats", "namespace_m_r_1_1_formats.html", "namespace_m_r_1_1_formats" ],
    [ "GUI", "namespace_m_r_1_1_g_u_i.html", "namespace_m_r_1_1_g_u_i" ],
    [ "Helper", "namespace_m_r_1_1_helper.html", "namespace_m_r_1_1_helper" ],
    [ "ImageIO", "namespace_m_r_1_1_image_i_o.html", "namespace_m_r_1_1_image_i_o" ],
    [ "Interp", "namespace_m_r_1_1_interp.html", "namespace_m_r_1_1_interp" ],
    [ "Math", "namespace_m_r_1_1_math.html", "namespace_m_r_1_1_math" ],
    [ "Mesh", "namespace_m_r_1_1_mesh.html", "namespace_m_r_1_1_mesh" ],
    [ "Path", "namespace_m_r_1_1_path.html", "namespace_m_r_1_1_path" ],
    [ "Registration", "namespace_m_r_1_1_registration.html", "namespace_m_r_1_1_registration" ],
    [ "Sparse", "namespace_m_r_1_1_sparse.html", "namespace_m_r_1_1_sparse" ],
    [ "Stats", "namespace_m_r_1_1_stats.html", "namespace_m_r_1_1_stats" ],
    [ "Thread", "namespace_m_r_1_1_thread.html", "namespace_m_r_1_1_thread" ],
    [ "BitSet", "class_m_r_1_1_bit_set.html", "class_m_r_1_1_bit_set" ],
    [ "compare_ptr_contents", "struct_m_r_1_1compare__ptr__contents.html", "struct_m_r_1_1compare__ptr__contents" ],
    [ "container_cast", "struct_m_r_1_1container__cast.html", "struct_m_r_1_1container__cast" ],
    [ "copy_ptr", "class_m_r_1_1copy__ptr.html", "class_m_r_1_1copy__ptr" ],
    [ "DataType", "class_m_r_1_1_data_type.html", "class_m_r_1_1_data_type" ],
    [ "enable_if_header_type", "struct_m_r_1_1enable__if__header__type.html", "struct_m_r_1_1enable__if__header__type" ],
    [ "enable_if_image_type", "struct_m_r_1_1enable__if__image__type.html", "struct_m_r_1_1enable__if__image__type" ],
    [ "Exception", "class_m_r_1_1_exception.html", "class_m_r_1_1_exception" ],
    [ "Header", "class_m_r_1_1_header.html", "class_m_r_1_1_header" ],
    [ "Histogram", "class_m_r_1_1_histogram.html", "class_m_r_1_1_histogram" ],
    [ "Image", "class_m_r_1_1_image.html", "class_m_r_1_1_image" ],
    [ "IntervalTimer", "class_m_r_1_1_interval_timer.html", "class_m_r_1_1_interval_timer" ],
    [ "InvalidImageException", "class_m_r_1_1_invalid_image_exception.html", "class_m_r_1_1_invalid_image_exception" ],
    [ "is_adapter_type", "struct_m_r_1_1is__adapter__type.html", "struct_m_r_1_1is__adapter__type" ],
    [ "is_complex", "struct_m_r_1_1is__complex.html", null ],
    [ "is_complex< std::complex< ValueType > >", "struct_m_r_1_1is__complex_3_01std_1_1complex_3_01_value_type_01_4_01_4.html", null ],
    [ "is_data_type", "struct_m_r_1_1is__data__type.html", null ],
    [ "is_header_type", "class_m_r_1_1is__header__type.html", "class_m_r_1_1is__header__type" ],
    [ "is_image_type", "class_m_r_1_1is__image__type.html", "class_m_r_1_1is__image__type" ],
    [ "is_pure_image", "struct_m_r_1_1is__pure__image.html", "struct_m_r_1_1is__pure__image" ],
    [ "Iterator", "class_m_r_1_1_iterator.html", "class_m_r_1_1_iterator" ],
    [ "Iterator_loop", "class_m_r_1_1_iterator__loop.html", "class_m_r_1_1_iterator__loop" ],
    [ "LogLevelLatch", "class_m_r_1_1_log_level_latch.html", "class_m_r_1_1_log_level_latch" ],
    [ "LoopAlongAxes", "struct_m_r_1_1_loop_along_axes.html", "struct_m_r_1_1_loop_along_axes" ],
    [ "LoopAlongAxesProgress", "struct_m_r_1_1_loop_along_axes_progress.html", "struct_m_r_1_1_loop_along_axes_progress" ],
    [ "LoopAlongAxisRange", "struct_m_r_1_1_loop_along_axis_range.html", "struct_m_r_1_1_loop_along_axis_range" ],
    [ "LoopAlongAxisRangeProgress", "struct_m_r_1_1_loop_along_axis_range_progress.html", "struct_m_r_1_1_loop_along_axis_range_progress" ],
    [ "LoopAlongDynamicAxes", "struct_m_r_1_1_loop_along_dynamic_axes.html", "struct_m_r_1_1_loop_along_dynamic_axes" ],
    [ "LoopAlongDynamicAxesProgress", "struct_m_r_1_1_loop_along_dynamic_axes_progress.html", "struct_m_r_1_1_loop_along_dynamic_axes_progress" ],
    [ "LoopAlongSingleAxis", "struct_m_r_1_1_loop_along_single_axis.html", "struct_m_r_1_1_loop_along_single_axis" ],
    [ "LoopAlongSingleAxisProgress", "struct_m_r_1_1_loop_along_single_axis_progress.html", "struct_m_r_1_1_loop_along_single_axis_progress" ],
    [ "LoopAlongStaticAxes", "struct_m_r_1_1_loop_along_static_axes.html", "struct_m_r_1_1_loop_along_static_axes" ],
    [ "LoopAlongStaticAxesProgress", "struct_m_r_1_1_loop_along_static_axes_progress.html", "struct_m_r_1_1_loop_along_static_axes_progress" ],
    [ "max_digits", "struct_m_r_1_1max__digits.html", "struct_m_r_1_1max__digits" ],
    [ "max_digits< X, typename std::enable_if< std::is_fundamental< typename X::Scalar >::value, int >::type >", "struct_m_r_1_1max__digits_3_01_x_00_01typename_01std_1_1enable__if_3_01std_1_1is__fundamental_3_8467db8cf8cb55f508d8abceaab32928.html", "struct_m_r_1_1max__digits_3_01_x_00_01typename_01std_1_1enable__if_3_01std_1_1is__fundamental_3_8467db8cf8cb55f508d8abceaab32928" ],
    [ "max_digits< X, typename std::enable_if< std::is_fundamental< typename X::value_type >::value &&!std::is_fundamental< typename X::Scalar >::value, int >::type >", "struct_m_r_1_1max__digits_3_01_x_00_01typename_01std_1_1enable__if_3_01std_1_1is__fundamental_3_1ef7ff8baa0d3893f596cbe7273651cd.html", "struct_m_r_1_1max__digits_3_01_x_00_01typename_01std_1_1enable__if_3_01std_1_1is__fundamental_3_1ef7ff8baa0d3893f596cbe7273651cd" ],
    [ "max_digits< X, typename std::enable_if< std::is_fundamental< X >::value, int >::type >", "struct_m_r_1_1max__digits_3_01_x_00_01typename_01std_1_1enable__if_3_01std_1_1is__fundamental_3_501364762f17ed6e57e6fc02375a30fa.html", "struct_m_r_1_1max__digits_3_01_x_00_01typename_01std_1_1enable__if_3_01std_1_1is__fundamental_3_501364762f17ed6e57e6fc02375a30fa" ],
    [ "Min_mem_array", "class_m_r_1_1_min__mem__array.html", "class_m_r_1_1_min__mem__array" ],
    [ "NeighbourhoodIterator", "class_m_r_1_1_neighbourhood_iterator.html", "class_m_r_1_1_neighbourhood_iterator" ],
    [ "ProgressBar", "class_m_r_1_1_progress_bar.html", "class_m_r_1_1_progress_bar" ],
    [ "ProgressInfo", "class_m_r_1_1_progress_info.html", "class_m_r_1_1_progress_info" ],
    [ "Random_loop", "class_m_r_1_1_random__loop.html", "class_m_r_1_1_random__loop" ],
    [ "Random_sparse_loop", "class_m_r_1_1_random__sparse__loop.html", "class_m_r_1_1_random__sparse__loop" ],
    [ "Timer", "class_m_r_1_1_timer.html", "class_m_r_1_1_timer" ],
    [ "Transform", "class_m_r_1_1_transform.html", "class_m_r_1_1_transform" ],
    [ "UnorderedMap", "struct_m_r_1_1_unordered_map.html", "struct_m_r_1_1_unordered_map" ]
];