var searchData=
[
  ['nameparser',['NameParser',['../class_m_r_1_1_file_1_1_name_parser.html',1,'MR::File']]],
  ['nbs',['NBS',['../class_m_r_1_1_connectome_1_1_enhance_1_1_n_b_s.html',1,'MR::Connectome::Enhance']]],
  ['nccprecomputefunctormasked_5fdebug',['NCCPrecomputeFunctorMasked_DEBUG',['../struct_m_r_1_1_registration_1_1_metric_1_1_n_c_c_precompute_functor_masked___d_e_b_u_g.html',1,'MR::Registration::Metric']]],
  ['nccprecomputefunctormasked_5fnaive',['NCCPrecomputeFunctorMasked_Naive',['../struct_m_r_1_1_registration_1_1_metric_1_1_n_c_c_precompute_functor_masked___naive.html',1,'MR::Registration::Metric']]],
  ['nearest',['Nearest',['../class_m_r_1_1_interp_1_1_nearest.html',1,'MR::Interp']]],
  ['nearest_3c_20mr_3a_3aimage_3c_20cfloat_20_3e_20_3e',['Nearest&lt; MR::Image&lt; cfloat &gt; &gt;',['../class_m_r_1_1_interp_1_1_nearest.html',1,'MR::Interp']]],
  ['nearest_3c_20mr_3a_3aimage_3c_20float_20_3e_20_3e',['Nearest&lt; MR::Image&lt; float &gt; &gt;',['../class_m_r_1_1_interp_1_1_nearest.html',1,'MR::Interp']]],
  ['neighbourhoodcoord',['NeighbourhoodCoord',['../class_m_r_1_1_adapter_1_1_neighbourhood_coord.html',1,'MR::Adapter']]],
  ['neighbourhooditerator',['NeighbourhoodIterator',['../class_m_r_1_1_neighbourhood_iterator.html',1,'MR']]],
  ['nifti1',['NIfTI1',['../class_m_r_1_1_formats_1_1_n_if_t_i1.html',1,'MR::Formats']]],
  ['nifti1_5fgz',['NIfTI1_GZ',['../class_m_r_1_1_formats_1_1_n_if_t_i1___g_z.html',1,'MR::Formats']]],
  ['nifti2',['NIfTI2',['../class_m_r_1_1_formats_1_1_n_if_t_i2.html',1,'MR::Formats']]],
  ['nifti2_5fgz',['NIfTI2_GZ',['../class_m_r_1_1_formats_1_1_n_if_t_i2___g_z.html',1,'MR::Formats']]],
  ['nifti_5f2_5fheader',['nifti_2_header',['../structnifti__2__header.html',1,'']]],
  ['node',['Node',['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_tool_1_1_node.html',1,'MR::GUI::MRView::Tool']]],
  ['node_5flist',['Node_list',['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_tool_1_1_node__list.html',1,'MR::GUI::MRView::Tool']]],
  ['node_5flist_5fmodel',['Node_list_model',['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_tool_1_1_node__list__model.html',1,'MR::GUI::MRView::Tool']]],
  ['node_5flist_5fview',['Node_list_view',['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_tool_1_1_node__list__view.html',1,'MR::GUI::MRView::Tool']]],
  ['nodecolourobserver',['NodeColourObserver',['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_tool_1_1_node_colour_observer.html',1,'MR::GUI::MRView::Tool']]],
  ['nodeoverlay',['NodeOverlay',['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_tool_1_1_node_overlay.html',1,'MR::GUI::MRView::Tool']]],
  ['nodeselectionsettings',['NodeSelectionSettings',['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_tool_1_1_node_selection_settings.html',1,'MR::GUI::MRView::Tool']]],
  ['nodeselectionsettingsdialog',['NodeSelectionSettingsDialog',['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_tool_1_1_node_selection_settings_dialog.html',1,'MR::GUI::MRView::Tool']]],
  ['nodeselectionsettingsframe',['NodeSelectionSettingsFrame',['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_tool_1_1_node_selection_settings_frame.html',1,'MR::GUI::MRView::Tool']]],
  ['nodeshader',['NodeShader',['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_tool_1_1_node_shader.html',1,'MR::GUI::MRView::Tool']]],
  ['nonlinear',['NonLinear',['../class_m_r_1_1_registration_1_1_non_linear.html',1,'MR::Registration']]],
  ['nonlinearkernel',['NonLinearKernel',['../class_m_r_1_1_registration_1_1_transform_1_1_non_linear_kernel.html',1,'MR::Registration::Transform']]],
  ['normal',['Normal',['../class_m_r_1_1_math_1_1_r_n_g_1_1_normal.html',1,'MR::Math::RNG']]],
  ['normal_3c_20float_20_3e',['Normal&lt; float &gt;',['../class_m_r_1_1_math_1_1_r_n_g_1_1_normal.html',1,'MR::Math::RNG']]],
  ['normalise',['Normalise',['../class_m_r_1_1_filter_1_1_normalise.html',1,'MR::Filter']]],
  ['normalise3d',['Normalise3D',['../class_m_r_1_1_adapter_1_1_normalise3_d.html',1,'MR::Adapter']]],
  ['normalisedcrosscorrelation',['NormalisedCrossCorrelation',['../class_m_r_1_1_registration_1_1_metric_1_1_normalised_cross_correlation.html',1,'MR::Registration::Metric']]],
  ['normmatrixelement',['NormMatrixElement',['../class_m_r_1_1_stats_1_1_c_f_e_1_1_norm_matrix_element.html',1,'MR::Stats::CFE']]],
  ['nulldist1',['NullDist1',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_algorithms_1_1_null_dist1.html',1,'MR::DWI::Tractography::Algorithms']]],
  ['nulldist2',['NullDist2',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_algorithms_1_1_null_dist2.html',1,'MR::DWI::Tractography::Algorithms']]]
];
