var searchData=
[
  ['base_0',['Base',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter::Base&lt; AdapterType, ImageType &gt;'],['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_resampling_1_1_base.html',1,'MR::DWI::Tractography::Resampling::Base'],['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_seeding_1_1_base.html',1,'MR::DWI::Tractography::Seeding::Base'],['../class_m_r_1_1_filter_1_1_base.html',1,'MR::Filter::Base'],['../class_m_r_1_1_fixel_1_1_filter_1_1_base.html',1,'MR::Fixel::Filter::Base'],['../class_m_r_1_1_formats_1_1_base.html',1,'MR::Formats::Base'],['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_mode_1_1_base.html',1,'MR::GUI::MRView::Mode::Base'],['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_tool_1_1_base.html',1,'MR::GUI::MRView::Tool::Base'],['../class_m_r_1_1_image_i_o_1_1_base.html',1,'MR::ImageIO::Base'],['../class_m_r_1_1_interp_1_1_base.html',1,'MR::Interp::Base&lt; ImageType &gt;'],['../class_m_r_1_1_registration_1_1_transform_1_1_base.html',1,'MR::Registration::Transform::Base'],['../class_m_r_1_1_surface_1_1_filter_1_1_base.html',1,'MR::Surface::Filter::Base']]],
  ['base_3c_20bootstrap_3c_20imagetype_2c_20functor_2c_20256_20_3e_2c_20imagetype_20_3e_1',['Base&lt; Bootstrap&lt; ImageType, Functor, 256 &gt;, ImageType &gt;',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter']]],
  ['base_3c_20extract1d_3c_20imagetype_20_3e_2c_20imagetype_20_3e_2',['Base&lt; Extract1D&lt; ImageType &gt;, ImageType &gt;',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter']]],
  ['base_3c_20extract_3c_20imagetype_20_3e_2c_20imagetype_20_3e_3',['Base&lt; Extract&lt; ImageType &gt;, ImageType &gt;',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter']]],
  ['base_3c_20gaussian1d_3c_20imagetype_20_3e_2c_20imagetype_20_3e_4',['Base&lt; Gaussian1D&lt; ImageType &gt;, ImageType &gt;',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter']]],
  ['base_3c_20gradient1d_3c_20imagetype_20_3e_2c_20imagetype_20_3e_5',['Base&lt; Gradient1D&lt; ImageType &gt;, ImageType &gt;',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter']]],
  ['base_3c_20jacobian_3c_20warptype_20_3e_2c_20warptype_20_3e_6',['Base&lt; Jacobian&lt; WarpType &gt;, WarpType &gt;',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter']]],
  ['base_3c_20median_3c_20imagetype_20_3e_2c_20imagetype_20_3e_7',['Base&lt; Median&lt; ImageType &gt;, ImageType &gt;',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter']]],
  ['base_3c_20neighbourhoodcoord_3c_20imagetype_20_3e_2c_20imagetype_20_3e_8',['Base&lt; NeighbourhoodCoord&lt; ImageType &gt;, ImageType &gt;',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter']]],
  ['base_3c_20normalise3d_3c_20imagetype_20_3e_2c_20imagetype_20_3e_9',['Base&lt; Normalise3D&lt; ImageType &gt;, ImageType &gt;',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter']]],
  ['base_3c_20permuteaxes_3c_20imagetype_20_3e_2c_20imagetype_20_3e_10',['Base&lt; PermuteAxes&lt; ImageType &gt;, ImageType &gt;',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter']]],
  ['base_3c_20regrid_3c_20imagetype_20_3e_2c_20imagetype_20_3e_11',['Base&lt; Regrid&lt; ImageType &gt;, ImageType &gt;',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter']]],
  ['base_3c_20replicate_3c_20imagetype_20_3e_2c_20imagetype_20_3e_12',['Base&lt; Replicate&lt; ImageType &gt;, ImageType &gt;',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter']]],
  ['base_3c_20subset_3c_20imagetype_20_3e_2c_20imagetype_20_3e_13',['Base&lt; Subset&lt; ImageType &gt;, ImageType &gt;',['../class_m_r_1_1_adapter_1_1_base.html',1,'MR::Adapter']]],
  ['basecrtp_14',['BaseCRTP',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_resampling_1_1_base_c_r_t_p.html',1,'MR::DWI::Tractography::Resampling']]],
  ['basecrtp_3c_20arc_20_3e_15',['BaseCRTP&lt; Arc &gt;',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_resampling_1_1_base_c_r_t_p.html',1,'MR::DWI::Tractography::Resampling']]],
  ['basecrtp_3c_20downsampler_20_3e_16',['BaseCRTP&lt; Downsampler &gt;',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_resampling_1_1_base_c_r_t_p.html',1,'MR::DWI::Tractography::Resampling']]],
  ['basecrtp_3c_20endpoints_20_3e_17',['BaseCRTP&lt; Endpoints &gt;',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_resampling_1_1_base_c_r_t_p.html',1,'MR::DWI::Tractography::Resampling']]],
  ['basecrtp_3c_20fixednumpoints_20_3e_18',['BaseCRTP&lt; FixedNumPoints &gt;',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_resampling_1_1_base_c_r_t_p.html',1,'MR::DWI::Tractography::Resampling']]],
  ['basecrtp_3c_20fixedstepsize_20_3e_19',['BaseCRTP&lt; FixedStepSize &gt;',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_resampling_1_1_base_c_r_t_p.html',1,'MR::DWI::Tractography::Resampling']]],
  ['basecrtp_3c_20upsampler_20_3e_20',['BaseCRTP&lt; Upsampler &gt;',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_resampling_1_1_base_c_r_t_p.html',1,'MR::DWI::Tractography::Resampling']]],
  ['basefixel_21',['BaseFixel',['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_tool_1_1_base_fixel.html',1,'MR::GUI::MRView::Tool']]],
  ['bitset_22',['BitSet',['../class_m_r_1_1_bit_set.html',1,'MR']]],
  ['bootstrap_23',['Bootstrap',['../class_m_r_1_1_d_w_i_1_1_bootstrap.html',1,'MR::DWI']]],
  ['buffer_24',['Buffer',['../class_m_r_1_1_image_1_1_buffer.html',1,'MR::Image']]],
  ['bufferscratchdump_25',['BufferScratchDump',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_mapping_1_1_buffer_scratch_dump.html',1,'MR::DWI::Tractography::Mapping']]]
];
