var searchData=
[
  ['mapped_5ftrack_5fbase',['Mapped_track_base',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_connectome_1_1_mapped__track__base.html',1,'MR::DWI::Tractography::Connectome']]],
  ['mapped_5ftrack_5fnodelist',['Mapped_track_nodelist',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_connectome_1_1_mapped__track__nodelist.html',1,'MR::DWI::Tractography::Connectome']]],
  ['mapped_5ftrack_5fnodepair',['Mapped_track_nodepair',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_connectome_1_1_mapped__track__nodepair.html',1,'MR::DWI::Tractography::Connectome']]],
  ['mapper',['Mapper',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_connectome_1_1_mapper.html',1,'MR::DWI::Tractography::Connectome']]],
  ['mapvoxel',['MapVoxel',['../class_m_r_1_1_d_w_i_1_1_fixel__map_1_1_map_voxel.html',1,'MR::DWI::Fixel_map']]],
  ['mapwriter',['MapWriter',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_mapping_1_1_map_writer.html',1,'MR::DWI::Tractography::Mapping']]],
  ['mapwriterbase',['MapWriterBase',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_mapping_1_1_map_writer_base.html',1,'MR::DWI::Tractography::Mapping']]],
  ['mask',['Mask',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_mask.html',1,'MR::DWI::Tractography']]],
  ['mask',['Mask',['../class_m_r_1_1_d_w_i_1_1_directions_1_1_mask.html',1,'MR::DWI::Directions']]],
  ['maskclean',['MaskClean',['../class_m_r_1_1_filter_1_1_mask_clean.html',1,'MR::Filter']]],
  ['mat2vec',['Mat2Vec',['../class_m_r_1_1_connectome_1_1_mat2_vec.html',1,'MR::Connectome']]],
  ['mat4',['mat4',['../class_m_r_1_1_g_u_i_1_1_g_l_1_1mat4.html',1,'MR::GUI::GL']]],
  ['matrix',['Matrix',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_connectome_1_1_matrix.html',1,'MR::DWI::Tractography::Connectome']]],
  ['matrix_5flist_5fmodel',['Matrix_list_model',['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_tool_1_1_matrix__list__model.html',1,'MR::GUI::MRView::Tool']]],
  ['max_5fdigits',['max_digits',['../struct_m_r_1_1max__digits.html',1,'MR']]],
  ['max_5fdigits_3c_20x_2c_20typename_20std_3a_3aenable_5fif_3c_20std_3a_3ais_5ffundamental_3c_20typename_20x_3a_3ascalar_20_3e_3a_3avalue_2c_20int_20_3e_3a_3atype_20_3e',['max_digits&lt; X, typename std::enable_if&lt; std::is_fundamental&lt; typename X::Scalar &gt;::value, int &gt;::type &gt;',['../struct_m_r_1_1max__digits_3_01_x_00_01typename_01std_1_1enable__if_3_01std_1_1is__fundamental_3_8467db8cf8cb55f508d8abceaab32928.html',1,'MR']]],
  ['max_5fdigits_3c_20x_2c_20typename_20std_3a_3aenable_5fif_3c_20std_3a_3ais_5ffundamental_3c_20typename_20x_3a_3avalue_5ftype_20_3e_3a_3avalue_20_26_26_21std_3a_3ais_5ffundamental_3c_20typename_20x_3a_3ascalar_20_3e_3a_3avalue_2c_20int_20_3e_3a_3atype_20_3e',['max_digits&lt; X, typename std::enable_if&lt; std::is_fundamental&lt; typename X::value_type &gt;::value &amp;&amp;!std::is_fundamental&lt; typename X::Scalar &gt;::value, int &gt;::type &gt;',['../struct_m_r_1_1max__digits_3_01_x_00_01typename_01std_1_1enable__if_3_01std_1_1is__fundamental_3_1ef7ff8baa0d3893f596cbe7273651cd.html',1,'MR']]],
  ['max_5fdigits_3c_20x_2c_20typename_20std_3a_3aenable_5fif_3c_20std_3a_3ais_5ffundamental_3c_20x_20_3e_3a_3avalue_2c_20int_20_3e_3a_3atype_20_3e',['max_digits&lt; X, typename std::enable_if&lt; std::is_fundamental&lt; X &gt;::value, int &gt;::type &gt;',['../struct_m_r_1_1max__digits_3_01_x_00_01typename_01std_1_1enable__if_3_01std_1_1is__fundamental_3_501364762f17ed6e57e6fc02375a30fa.html',1,'MR']]],
  ['meansquared',['MeanSquared',['../class_m_r_1_1_registration_1_1_metric_1_1_mean_squared.html',1,'MR::Registration::Metric']]],
  ['meansquared4d',['MeanSquared4D',['../class_m_r_1_1_registration_1_1_metric_1_1_mean_squared4_d.html',1,'MR::Registration::Metric']]],
  ['meansquarednogradient',['MeanSquaredNoGradient',['../class_m_r_1_1_registration_1_1_metric_1_1_mean_squared_no_gradient.html',1,'MR::Registration::Metric']]],
  ['meansquarednogradient4d',['MeanSquaredNoGradient4D',['../class_m_r_1_1_registration_1_1_metric_1_1_mean_squared_no_gradient4_d.html',1,'MR::Registration::Metric']]],
  ['meansquaredvectornogradient4d',['MeanSquaredVectorNoGradient4D',['../class_m_r_1_1_registration_1_1_metric_1_1_mean_squared_vector_no_gradient4_d.html',1,'MR::Registration::Metric']]],
  ['median',['Median',['../class_m_r_1_1_adapter_1_1_median.html',1,'MR::Adapter']]],
  ['median',['Median',['../class_m_r_1_1_filter_1_1_median.html',1,'MR::Filter']]],
  ['mesh',['Mesh',['../class_m_r_1_1_mesh_1_1_mesh.html',1,'MR::Mesh']]],
  ['meshmulti',['MeshMulti',['../class_m_r_1_1_mesh_1_1_mesh_multi.html',1,'MR::Mesh']]],
  ['methodbase',['MethodBase',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_tracking_1_1_method_base.html',1,'MR::DWI::Tractography::Tracking']]],
  ['metric',['Metric',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_connectome_1_1_metric.html',1,'MR::DWI::Tractography::Connectome']]],
  ['mgh',['MGH',['../class_m_r_1_1_formats_1_1_m_g_h.html',1,'MR::Formats']]],
  ['mgz',['MGZ',['../class_m_r_1_1_formats_1_1_m_g_z.html',1,'MR::Formats']]],
  ['mhsampler',['MHSampler',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_g_t_1_1_m_h_sampler.html',1,'MR::DWI::Tractography::GT']]],
  ['min_5fmem_5farray',['Min_mem_array',['../class_m_r_1_1_min__mem__array.html',1,'MR']]],
  ['min_5fmem_5farray_3c_20track_5ffixel_5fcontribution_20_3e',['Min_mem_array&lt; Track_fixel_contribution &gt;',['../class_m_r_1_1_min__mem__array.html',1,'MR']]],
  ['mmap',['MMap',['../class_m_r_1_1_file_1_1_m_map.html',1,'MR::File']]],
  ['modeguivisitor',['ModeGuiVisitor',['../class_m_r_1_1_g_u_i_1_1_m_r_view_1_1_mode_1_1_mode_gui_visitor.html',1,'MR::GUI::MRView::Mode']]],
  ['model',['Model',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_s_i_f_t_1_1_model.html',1,'MR::DWI::Tractography::SIFT']]],
  ['modelbase',['ModelBase',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_s_i_f_t_1_1_model_base.html',1,'MR::DWI::Tractography::SIFT']]],
  ['modelbase_3c_20fixel_5ftd_5fseed_20_3e',['ModelBase&lt; Fixel_TD_seed &gt;',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_s_i_f_t_1_1_model_base.html',1,'MR::DWI::Tractography::SIFT']]],
  ['momentsinitialiser',['MomentsInitialiser',['../class_m_r_1_1_registration_1_1_transform_1_1_init_1_1_moments_initialiser.html',1,'MR::Registration::Transform::Init']]],
  ['mosaic',['Mosaic',['../class_m_r_1_1_image_i_o_1_1_mosaic.html',1,'MR::ImageIO']]],
  ['mri',['MRI',['../class_m_r_1_1_formats_1_1_m_r_i.html',1,'MR::Formats']]],
  ['mrtrix',['MRtrix',['../class_m_r_1_1_formats_1_1_m_rtrix.html',1,'MR::Formats']]],
  ['mrtrix_5fgz',['MRtrix_GZ',['../class_m_r_1_1_formats_1_1_m_rtrix___g_z.html',1,'MR::Formats']]],
  ['mrtrix_5fsparse',['MRtrix_sparse',['../class_m_r_1_1_formats_1_1_m_rtrix__sparse.html',1,'MR::Formats']]],
  ['msmt_5fcsd',['MSMT_CSD',['../class_m_r_1_1_d_w_i_1_1_s_deconv_1_1_m_s_m_t___c_s_d.html',1,'MR::DWI::SDeconv']]],
  ['mt_5fgradient_5fvector_5fsorter',['MT_gradient_vector_sorter',['../class_m_r_1_1_d_w_i_1_1_tractography_1_1_s_i_f_t_1_1_m_t__gradient__vector__sorter.html',1,'MR::DWI::Tractography::SIFT']]]
];
